alg_name: "UNKE"
model_name: "Qwen/Qwen2.5-3B-Instruct"
device: 0
layers: [5]
clamp_norm_factor: 4
layer_selection: "all"
fact_token: "last"
lr: 2e-4
v_num_grad_steps: 100
v_lr: 5e-1
v_loss_layer: 35
v_weight_decay: 1e-2
optim_num_step: 100
ex_data_num: 20
rewrite_module_tmp: "model.layers.{}.mlp.down_proj"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "model.embed_tokens"